# Generated by Django 5.2.13 on 2026-04-13 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomDatabase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.URLField()),
                ('api_key', models.CharField(blank=True, max_length=500, null=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Additional configuration (headers, query params, auth type, etc.)')),
                ('adapter_type', models.CharField(default='rest_api', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_tested', models.DateTimeField(blank=True, null=True)),
                ('test_result', models.TextField(blank=True, null=True)),
                ('test_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom database',
                'verbose_name_plural': 'Custom databases',
                'ordering': ['-created_at'],
            },
        ),
    ]
