"""
SnakeMake workflow generator for NeuroWorkflow.

This module generates SnakeMake workflows from NeuroWorkflow execution sequences,
enabling HPC job submission and distributed execution.
"""

import os
from typing import Dict, List, Any, Optional
from ..core.schema import PortType, ResourceRequirements


def generate_snakemake_workflow(
    execution_sequence: Dict[str, Any],
    output_dir: str = "./output",
    workflow_name: Optional[str] = None,
    resource_requirements: Optional[ResourceRequirements] = None,
    add_metadata: bool = True
) -> Dict[str, str]:
    """
    Generate SnakeMake workflow from execution sequence.
    
    Args:
        execution_sequence: Dictionary with execution sequence from WorkflowBuilder
        output_dir: Directory for output files
        workflow_name: Name for the workflow (defaults to execution_sequence name)
        resource_requirements: Resource requirements for jobs
        add_metadata: Add workflow metadata as comments
    
    Returns:
        Dictionary with paths to generated files (Snakefile, config.yaml)
    """
    
    workflow_name = workflow_name or execution_sequence.get('workflow_name', 'neuro_workflow')
    sequence = execution_sequence['execution_sequence']
    
    print(f"Generating SnakeMake workflow: {workflow_name}")
    print(f"Total nodes in execution order: {len(sequence)}")
    
    # Create output directory
    os.makedirs(output_dir, exist_ok=True)
    
    # Generate Snakefile
    snakefile_path = os.path.join(output_dir, "Snakefile")
    snakefile_content = _generate_snakefile(
        sequence, workflow_name, resource_requirements, add_metadata
    )
    
    with open(snakefile_path, 'w') as f:
        f.write(snakefile_content)
    
    print(f"  Snakefile generated: {snakefile_path}")
    
    # Generate config file
    config_path = os.path.join(output_dir, "config.yaml")
    config_content = _generate_config_file(
        workflow_name, sequence, resource_requirements
    )
    
    with open(config_path, 'w') as f:
        f.write(config_content)
    
    print(f"  Config file generated: {config_path}")
    
    return {
        'snakefile': snakefile_path,
        'config': config_path
    }


def _generate_snakefile(
    sequence: List[Dict[str, Any]],
    workflow_name: str,
    resource_requirements: Optional[ResourceRequirements],
    add_metadata: bool
) -> str:
    """Generate Snakefile content."""
    
    lines = []
    
    # Header with metadata
    if add_metadata:
        lines.extend([
            f"# SnakeMake Workflow: {workflow_name}",
            f"# Generated by NeuroWorkflow",
            f"# This workflow was automatically generated from a NeuroWorkflow execution",
            "",
            "# Configuration",
            "configfile: 'config.yaml'",
            "",
        ])
    else:
        lines.extend([
            "configfile: 'config.yaml'",
            "",
        ])
    
    # Import Python modules if needed
    lines.extend([
        "import os",
        "",
    ])
    
    # Generate rules for each node
    input_files = []
    output_files = []
    
    for i, entry in enumerate(sequence):
        node_name = entry['node_name']
        node_type = entry.get('node_type', 'unknown')
        node_instance = entry.get('node_instance')
        
        # Get input and output ports
        inputs = _extract_io_ports(node_instance, is_input=True) if node_instance else []
        outputs = _extract_io_ports(node_instance, is_input=False) if node_instance else []
        
        # Generate rule
        rule_name = _sanitize_rule_name(node_name)
        rule_content = _generate_rule(
            rule_name, node_name, node_type, inputs, outputs, 
            entry, resource_requirements, i
        )
        lines.extend(rule_content)
        lines.append("")
        
        # Track files
        input_files.extend(inputs)
        output_files.extend(outputs)
    
    # Add all rule (final outputs)
    if output_files:
        lines.extend([
            "rule all:",
            "    input:",
        ])
        for output_file in output_files:
            lines.append(f"        '{output_file}',")
        lines.append("")
    
    return '\n'.join(lines)


def _generate_rule(
    rule_name: str,
    node_name: str,
    node_type: str,
    inputs: List[str],
    outputs: List[str],
    entry: Dict[str, Any],
    resource_requirements: Optional[ResourceRequirements],
    execution_order: int
) -> List[str]:
    """Generate a single SnakeMake rule."""
    
    lines = []
    
    # Rule header
    lines.append(f"rule {rule_name}:")
    lines.append(f"    # Node: {node_name} ({node_type})")
    lines.append(f"    # Execution order: {execution_order}")
    
    # Input files
    if inputs:
        lines.append("    input:")
        for inp in inputs:
            lines.append(f"        '{inp}',")
    else:
        lines.append("    input:")
        lines.append("        # No file inputs")
    
    # Output files
    if outputs:
        lines.append("    output:")
        for out in outputs:
            lines.append(f"        '{out}',")
    else:
        # If no file outputs, create a placeholder output
        output_file = f"output/{rule_name}_completed.txt"
        lines.append("    output:")
        lines.append(f"        '{output_file}',")
        outputs = [output_file]
    
    # Resources
    if resource_requirements:
        lines.append("    resources:")
        lines.append(f"        cpus={resource_requirements.cpus},")
        lines.append(f"        mem_mb=int({resource_requirements.memory_gb * 1024}),")
        if resource_requirements.gpus > 0:
            lines.append(f"        gpus={resource_requirements.gpus},")
    
    # Shell command - generate Python script execution
    python_script = _generate_node_python_script(entry)
    script_file = f"scripts/{rule_name}.py"
    
    lines.append("    shell:")
    lines.append(f"        \"\"\"")
    lines.append(f"        # Save Python script")
    lines.append(f"        mkdir -p scripts")
    lines.append(f"        cat > {script_file} << 'PYTHON_SCRIPT'")
    lines.append(f"{python_script}")
    lines.append(f"PYTHON_SCRIPT")
    lines.append(f"        # Execute script")
    lines.append(f"        python {script_file}")
    lines.append(f"        # Mark completion")
    lines.append(f"        touch {{output}}")
    lines.append(f"        \"\"\"")
    
    return lines


def _extract_io_ports(node_instance, is_input: bool) -> List[str]:
    """Extract I/O port file paths from node instance."""
    
    ports = node_instance._input_ports if is_input else node_instance._output_ports
    file_paths = []
    
    for port_name, port in ports.items():
        # Check if port is I/O type
        port_def = getattr(port, 'definition', None)
        if port_def:
            if hasattr(port_def, 'is_io_port') and port_def.is_io_port():
                # Get file path from port value
                value = port.value
                if value and isinstance(value, str):
                    file_paths.append(value)
                elif value and isinstance(value, dict) and 'path' in value:
                    file_paths.append(value['path'])
    
    return file_paths


def _sanitize_rule_name(name: str) -> str:
    """Convert node name to valid SnakeMake rule name."""
    # Replace spaces and special chars with underscores
    sanitized = name.replace(' ', '_').replace('-', '_')
    # Remove invalid characters
    sanitized = ''.join(c if c.isalnum() or c == '_' else '_' for c in sanitized)
    # Ensure it starts with a letter
    if sanitized and not sanitized[0].isalpha():
        sanitized = 'rule_' + sanitized
    return sanitized.lower()


def _generate_node_python_script(entry: Dict[str, Any]) -> str:
    """Generate Python script for a node rule."""
    
    node_instance = entry.get('node_instance')
    
    # Try to get existing Python script from node
    if node_instance and hasattr(node_instance, '_output_ports'):
        python_port = node_instance._output_ports.get('python_script')
        if python_port and python_port.value:
            return python_port.value
    
    # Fallback: generate basic script
    node_name = entry['node_name']
    return f"""# Generated script for {node_name}
import sys
# Node execution code would go here
print("Executing node: {node_name}")
"""


def _generate_config_file(
    workflow_name: str,
    sequence: List[Dict[str, Any]],
    resource_requirements: Optional[ResourceRequirements]
) -> str:
    """Generate SnakeMake config file."""
    
    lines = [
        f"# SnakeMake Configuration for: {workflow_name}",
        "",
        "workflow:",
        f"  name: {workflow_name}",
        f"  nodes: {len(sequence)}",
        "",
    ]
    
    if resource_requirements:
        lines.extend([
            "resources:",
            f"  default_cpus: {resource_requirements.cpus}",
            f"  default_memory_gb: {resource_requirements.memory_gb}",
            f"  default_gpus: {resource_requirements.gpus}",
            f"  default_walltime_hours: {resource_requirements.walltime_hours}",
            "",
        ])
        if resource_requirements.queue:
            lines.append(f"  queue: {resource_requirements.queue}")
        if resource_requirements.account:
            lines.append(f"  account: {resource_requirements.account}")
        lines.append("")
    
    # Node-specific configurations
    lines.extend([
        "nodes:",
    ])
    
    for entry in sequence:
        node_name = entry['node_name']
        rule_name = _sanitize_rule_name(node_name)
        lines.append(f"  {rule_name}:")
        lines.append(f"    name: {node_name}")
        lines.append(f"    type: {entry.get('node_type', 'unknown')}")
        lines.append("")
    
    return '\n'.join(lines)

