# Workflow Script: Simple population of spiking neurons
# Generated: 2026-02-02 17:06:33
# Original execution: 2026-02-02 17:06:31
# Execution order: ['Cholinergic Interneuron', 'ChIN_population', 'spike detector for ChIN pop', 'direct current stimulation', 'poisson_stimulation noise', 'Spiny Projection Neuron', 'SPN_population', 'spike detector for SPN pop', 'connection from ChINs to SPNs.', 'connection from SPNs to ChINs.']
# Total nodes: 10

# This script was automatically generated from NeuroWorkflow execution
# Each section corresponds to a node that was executed in the workflow

# === IMPORTS ===
import nest
import numpy as np

# === Cholinergic Interneuron (single_neuron_builder) ===
# Execution order: 0
# Single Neuron: Cholinergic Interneuron (ChIN)
# Generated by NeuroWorkflow SingleNeuronBuilderNode
# Model Type: point_process
# Cell Class: excitatory


# === BIOLOGICAL PROPERTIES ===
# Dendrite extent: 300.0 μm
# Dendrite diameter: 2.5 μm
# Neurotransmitters: ['AMPA', 'NMDA']
# PSP amplitudes: {'AMPA': 0.4, 'NMDA': 0.4}
# Rise times: {'AMPA': 2.0, 'NMDA': 2.0}
# Firing rates - Resting: [6.0, 10.0] Hz
# Firing rates - Active: [25.0, 60.0] Hz
# Firing rates - Maximum: [70.0, 120.0] Hz

# === NEST MODEL CREATION ===
nest.CopyModel("iaf_psc_alpha_multisynapse", "iaf_psc_alpha_multisynapse_ChIN_custom")

# Multisynapse model: map PSP rise times to tau_syn
# AMPA: 2.0 ms
# NMDA: 2.0 ms
nest.SetDefaults("iaf_psc_alpha_multisynapse_ChIN_custom", {
                        "V_th": -50.0,
                        "C_m": 200.0,
                        "tau_m": 15.0,
                        "V_reset": -70.0,
                        "t_ref": 2.0,
                        "I_e": 210.0,
                        "tau_syn": [
                            2.0,
                            2.0
                        ]
                    })
chin = nest.Create("iaf_psc_alpha_multisynapse_ChIN_custom", 1)

print(f"Created neuron: {chin}")
print(f"Model template: iaf_psc_alpha_multisynapse_ChIN_custom")

# === ChIN_population (population_builder) ===
# Execution order: 1
# Population: Cholinergic Interneurons (ChIN)
# Generated by NeuroWorkflow PopulationBuilderNode
# Brain Region: Striatum
# Population Size: 150 neurons (single hemisphere)
# Model Type: point_process
# Spatial: 3D


# === POPULATION BIOLOGICAL CONTEXT ===
# Density: 25000 neurons/mm³
# Tissue volume: 0.2 mm³
# Reference: Schüz & Palm (1989)
# Species: human
# Estimation method: stereological counting
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# === SPATIAL POSITIONS ===
# 3D positions for 150 neurons
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# Generate spatial positions
positions = np.zeros((150, 3))
positions[:, 0] = np.random.uniform(0.0, 2.0, 150)  # x coordinates
positions[:, 1] = np.random.uniform(0.0, 2.0, 150)  # y coordinates
positions[:, 2] = np.random.uniform(0.0, 1.0, 150)  # z coordinates

# === POPULATION CREATION ===
# Using neuron model from SingleNeuronBuilderNode: iaf_psc_alpha_multisynapse_ChIN_custom
# Create population with 3D spatial positions
nest_positions = nest.spatial.free(positions.tolist())
chin = nest.Create("iaf_psc_alpha_multisynapse_ChIN_custom", 150, positions=nest_positions)

# Print status of one neuron from the population
neuron_status = nest.GetStatus(chin[0])
print(f"Status of first neuron: {neuron_status}")

# === POPULATION SUMMARY ===
print(f"Created population: {len(chin)} Cholinergic Interneurons")
print(f"Population IDs: {chin}")
print(f"Model: iaf_psc_alpha_multisynapse_ChIN_custom")
print(f"Spatial organization: 3D positions")

# === spike detector for ChIN pop (recording_builder) ===
# Execution order: 2
# === RECORDING SETUP ===
# Generated by SNNbuilder_Recordable: spike detector for ChIN pop
# Recording type: spike_recorder


# Spike recorder parameters
spike_params = {
    "record_to": "ascii",
    "start": 0.0,
    "stop": 1000.0
}

# Create 1 spike_recorder device(s)
recorders = nest.Create('spike_recorder', 1, params=spike_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# chin = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Full population
target_neurons = chin

# Create connections (efficient approach)
# Recording devices: Direct connections (no synapse properties needed)
nest.Connect(target_neurons, recorders)
# Note: Recording devices receive spikes directly, no synaptic transmission

print(f'Created 1 recording devices')
print(f'Connected {len(target_neurons)} target neurons')

# === direct current stimulation (stimulation_builder) ===
# Execution order: 3
# === STIMULATION SETUP ===
# Generated by SNNbuilder_Stimulation: direct current stimulation
# Stimulation type: dc_generator


# DC generator parameters
dc_params = {
    "label": "dc_stim",
    "start": 500.0,
    "stop": 700.0,
    "amplitude": 100.0
}

# Create 1 dc_generator device(s)
devices = nest.Create('dc_generator', 1, params=dc_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# chin = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Full population
target_neurons = chin

# Create connections (efficient approach)
# DC generator: Direct current injection (no synapse properties needed)
nest.Connect(devices, target_neurons)
# Note: DC generators inject current directly, no synaptic transmission

print(f'Created 1 stimulation devices')
print(f'Connected to {{len(target_neurons)}} target neurons')

# === poisson_stimulation noise (stimulation_builder) ===
# Execution order: 4
# === STIMULATION SETUP ===
# Generated by SNNbuilder_Stimulation: poisson_stimulation noise
# Stimulation type: poisson_generator


# Poisson generator parameters
poisson_params = {
    "rate": 50.0,
    "start": 100.0,
    "stop": 900.0
}

# Synapse specification
synapse_spec = {
    "synapse_model": "static_synapse",
    "weight": 2.5,
    "delay": 1.5,
    "receptor_type": 1
}

# Create custom synapse model
custom_synapse_name = 'static_synapse_custom_poisson_stimulation_noise'
nest.CopyModel('static_synapse', custom_synapse_name)

# Create 1 poisson_generator device(s)
devices = nest.Create('poisson_generator', 1, params=poisson_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# chin = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Full population
target_neurons = chin

# Create connections (efficient approach)
sdict = {
    'synapse_model': custom_synapse_name,
    'weight': 2.5,
    'delay': 1.5,
    'receptor_type': 1  # User-defined for multisynapse target
}

# Efficient connection: no need to iterate over devices
# Single Poisson device to many neurons (all-to-all)
nest.Connect(devices, target_neurons, syn_spec=sdict)

print(f'Created 1 stimulation devices')
print(f'Connected to {{len(target_neurons)}} target neurons')

# === Spiny Projection Neuron (single_neuron_builder) ===
# Execution order: 5
# Single Neuron: Spiny Projection Neuron (SPN)
# Generated by NeuroWorkflow SingleNeuronBuilderNode
# Model Type: point_process
# Cell Class: inhibitory


# === BIOLOGICAL PROPERTIES ===
# Dendrite extent: 300.0 μm
# Dendrite diameter: 2.5 μm
# Neurotransmitters: ['GABA']
# PSP amplitudes: {'GABA': 0.4}
# Rise times: {'GABA': 2.0}
# Firing rates - Resting: [2.0, 8.0] Hz
# Firing rates - Active: [15.0, 40.0] Hz
# Firing rates - Maximum: [60.0, 120.0] Hz

# === NEST MODEL CREATION ===
nest.CopyModel("iaf_psc_alpha_multisynapse", "iaf_psc_alpha_multisynapse_SPN_custom")

# Multisynapse model: map PSP rise times to tau_syn
# GABA: 2.0 ms
nest.SetDefaults("iaf_psc_alpha_multisynapse_SPN_custom", {
                        "V_th": -50.0,
                        "C_m": 200.0,
                        "tau_m": 15.0,
                        "V_reset": -70.0,
                        "t_ref": 2.0,
                        "I_e": 200.0,
                        "tau_syn": [
                            2.0
                        ]
                    })
spn = nest.Create("iaf_psc_alpha_multisynapse_SPN_custom", 1)

print(f"Created neuron: {spn}")
print(f"Model template: iaf_psc_alpha_multisynapse_SPN_custom")

# === SPN_population (population_builder) ===
# Execution order: 6
# Population: Spiny Projection Neurons (SPN)
# Generated by NeuroWorkflow PopulationBuilderNode
# Brain Region: Striatum
# Population Size: 8000 neurons (single hemisphere)
# Model Type: point_process
# Spatial: 3D


# === POPULATION BIOLOGICAL CONTEXT ===
# Density: 25000 neurons/mm³
# Tissue volume: 0.2 mm³
# Reference: Schüz & Palm (1989)
# Species: human
# Estimation method: stereological counting
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# === SPATIAL POSITIONS ===
# 3D positions for 8000 neurons
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# Generate spatial positions
positions = np.zeros((8000, 3))
positions[:, 0] = np.random.uniform(0.0, 2.0, 8000)  # x coordinates
positions[:, 1] = np.random.uniform(0.0, 2.0, 8000)  # y coordinates
positions[:, 2] = np.random.uniform(0.0, 1.0, 8000)  # z coordinates

# === POPULATION CREATION ===
# Using neuron model from SingleNeuronBuilderNode: iaf_psc_alpha_multisynapse_SPN_custom
# Create population with 3D spatial positions
nest_positions = nest.spatial.free(positions.tolist())
spn = nest.Create("iaf_psc_alpha_multisynapse_SPN_custom", 8000, positions=nest_positions)

# Print status of one neuron from the population
neuron_status = nest.GetStatus(spn[0])
print(f"Status of first neuron: {neuron_status}")

# === POPULATION SUMMARY ===
print(f"Created population: {len(spn)} Spiny Projection Neurons")
print(f"Population IDs: {spn}")
print(f"Model: iaf_psc_alpha_multisynapse_SPN_custom")
print(f"Spatial organization: 3D positions")

# === spike detector for SPN pop (recording_builder) ===
# Execution order: 7
# === RECORDING SETUP ===
# Generated by SNNbuilder_Recordable: spike detector for SPN pop
# Recording type: spike_recorder


# Spike recorder parameters
spike_params = {
    "record_to": "ascii",
    "start": 0.0,
    "stop": 1000.0
}

# Create 1 spike_recorder device(s)
recorders = nest.Create('spike_recorder', 1, params=spike_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# spn = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Full population
target_neurons = spn

# Create connections (efficient approach)
# Recording devices: Direct connections (no synapse properties needed)
nest.Connect(target_neurons, recorders)
# Note: Recording devices receive spikes directly, no synaptic transmission

print(f'Created 1 recording devices')
print(f'Connected {len(target_neurons)} target neurons')

# === connection from ChINs to SPNs. (connection_builder) ===
# Execution order: 8
# Neural Connection: ChIN_SPN indegree
# Generated by NeuroWorkflow ConnectionBuilderNode
# Timestamp: 2026-02-02 17:06:31


# Connection: ChIN_SPN indegree
# Type: excitatory
# Rule: fixed_indegree

# === SYNAPSE MODEL SETUP ===
base_synapse = 'static_synapse'
custom_synapse = 'static_synapse_custom_connection_from_ChINs_to_SPNs.'

# Copy base synapse model
nest.CopyModel(base_synapse, custom_synapse)

# === CONNECTION DICTIONARY ===
cdict = {'allow_autapses': False, 'rule': 'fixed_indegree', 'indegree': 1, 'allow_multapses': False, 'mask': {'spherical': {'radius': 0.5}}}

# === SYNAPSE DICTIONARY (User-defined weight) ===
# User provided weight in synapse_dict
# Target is multisynapse: True

# Multisynapse target - receptor mapping: {'GABA': 1}
# Source cell_class: excitatory
# Using receptor: GABA (receptor_type: 1)
sdict = {'synapse_model': 'static_synapse_custom_connection_from_ChINs_to_SPNs.', 'weight': 10.0, 'delay': 1.0, 'receptor_type': 1}

# === CREATE CONNECTIONS ===
# Note: Make sure you have defined your population variables:
# chin = your_source_population
# spn = your_target_population

# Create connections (single synapse dict - user-defined weight)
nest.Connect(chin, spn, cdict, sdict)

# Get connection information
# connections = nest.GetConnections(chin, spn)
# print(f'Created {{len(connections)}} connections')

# === BIOLOGICAL PROPERTIES ===
# Axon organization: focused (radius: 0.5 mm)
# Projection percentage: 100.0%
# Bouton number: 50
# Receptor location: none (None)
# Redundancy: 100.0
# Base weight: 10.0 (effective weight calculated at runtime)

# === connection from SPNs to ChINs. (connection_builder) ===
# Execution order: 9
# Neural Connection: SPN_ChIN indegree
# Generated by NeuroWorkflow ConnectionBuilderNode
# Timestamp: 2026-02-02 17:06:31


# Connection: SPN_ChIN indegree
# Type: inhibitory
# Rule: fixed_indegree

# === SYNAPSE MODEL SETUP ===
base_synapse = 'static_synapse'
custom_synapse = 'static_synapse_custom_connection_from_SPNs_to_ChINs.'

# Copy base synapse model
nest.CopyModel(base_synapse, custom_synapse)

# === CONNECTION DICTIONARY ===
cdict = {'allow_autapses': False, 'rule': 'fixed_indegree', 'indegree': 27, 'allow_multapses': False, 'mask': {'spherical': {'radius': 0.5}}}

# === SYNAPSE DICTIONARY (User-defined weight) ===
# User provided weight in synapse_dict
# Target is multisynapse: True

# Multisynapse target - receptor mapping: {'AMPA': 1, 'NMDA': 2}
# Source cell_class: inhibitory
# Using receptor: AMPA (receptor_type: 1)
sdict = {'synapse_model': 'static_synapse_custom_connection_from_SPNs_to_ChINs.', 'weight': -4.0, 'delay': 1.0, 'receptor_type': 1}

# === CREATE CONNECTIONS ===
# Note: Make sure you have defined your population variables:
# spn = your_source_population
# chin = your_target_population

# Create connections (single synapse dict - user-defined weight)
nest.Connect(spn, chin, cdict, sdict)

# Get connection information
# connections = nest.GetConnections(spn, chin)
# print(f'Created {{len(connections)}} connections')

# === BIOLOGICAL PROPERTIES ===
# Axon organization: focused (radius: 0.5 mm)
# Projection percentage: 100.0%
# Bouton number: 50
# Receptor location: none (None)
# Redundancy: 100.0
# Base weight: 4.0 (effective weight calculated at runtime)
