# Workflow Script: Simple population of spiking neurons
# Generated: 2026-02-02 17:11:10
# Original execution: 2026-02-02 17:11:06
# Execution order: ['Parvalbumin-expressing interneuron', 'inhibitory cortical population', 'pyramidal neuron', 'cortical_population', 'spike detector for some neurons at Inh. pop', 'spike detector for Exc. pop', 'direct current stimulation', 'poisson_stimulation noise', 'connection from Inh to Exc Neurons', 'connection from Exc. to Inh Neurons.']
# Total nodes: 10

# This script was automatically generated from NeuroWorkflow execution
# Each section corresponds to a node that was executed in the workflow

# === IMPORTS ===
import nest
import numpy as np

# === Parvalbumin-expressing interneuron (single_neuron_builder) ===
# Execution order: 0
# Single Neuron: PV interneuron (PV)
# Generated by NeuroWorkflow SingleNeuronBuilderNode
# Model Type: point_process
# Cell Class: inhibitory


# === BIOLOGICAL PROPERTIES ===
# Dendrite extent: 200.0 μm
# Dendrite diameter: 2.0 μm
# Neurotransmitters: ['AMPA', 'NMDA']
# PSP amplitudes: {'AMPA': 0.5, 'NMDA': 0.3}
# Rise times: {'AMPA': 2.0, 'NMDA': 10.0}
# Firing rates - Resting: [1.0, 5.0] Hz
# Firing rates - Active: [10.0, 30.0] Hz
# Firing rates - Maximum: [50.0, 100.0] Hz

# === NEST MODEL CREATION ===
nest.CopyModel("iaf_psc_alpha", "iaf_psc_alpha_PV_custom")

# Inhibitory cell class defaults applied:
# V_th: -52.0
# V_reset: -65.0
# tau_m: 10.0
# t_ref: 1.0
nest.SetDefaults("iaf_psc_alpha_PV_custom", {
                        "C_m": 200.0,
                        "V_th": -52.0,
                        "V_reset": -65.0,
                        "tau_m": 10.0,
                        "t_ref": 1.0
                    })
pv = nest.Create("iaf_psc_alpha_PV_custom", 1)

print(f"Created neuron: {pv}")
print(f"Model template: iaf_psc_alpha_PV_custom")

# === inhibitory cortical population (population_builder) ===
# Execution order: 1
# Population: Layer of PV neurons (PVpop)
# Generated by NeuroWorkflow PopulationBuilderNode
# Brain Region: Primary Visual Cortex
# Population Size: 100 neurons (single hemisphere)
# Model Type: point_process
# Spatial: 3D


# === POPULATION BIOLOGICAL CONTEXT ===
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# === SPATIAL POSITIONS ===
# 3D positions for 100 neurons
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# Generate spatial positions
positions = np.zeros((100, 3))
positions[:, 0] = np.random.uniform(0.0, 2.0, 100)  # x coordinates
positions[:, 1] = np.random.uniform(0.0, 2.0, 100)  # y coordinates
positions[:, 2] = np.random.uniform(0.0, 1.0, 100)  # z coordinates

# === POPULATION CREATION ===
# Using neuron model from SingleNeuronBuilderNode: iaf_psc_alpha_PV_custom
# Create population with 3D spatial positions
nest_positions = nest.spatial.free(positions.tolist())
pvpop = nest.Create("iaf_psc_alpha_PV_custom", 100, positions=nest_positions)

# Print status of one neuron from the population
neuron_status = nest.GetStatus(pvpop[0])
print(f"Status of first neuron: {neuron_status}")

# === POPULATION SUMMARY ===
print(f"Created population: {len(pvpop)} Layer of PV neurons")
print(f"Population IDs: {pvpop}")
print(f"Model: iaf_psc_alpha_PV_custom")
print(f"Spatial organization: 3D positions")

# === pyramidal neuron (single_neuron_builder) ===
# Execution order: 2
# Single Neuron: Pyramidal Neuron L2/3 (PyL23)
# Generated by NeuroWorkflow SingleNeuronBuilderNode
# Model Type: point_process
# Cell Class: excitatory


# === BIOLOGICAL PROPERTIES ===
# Dendrite extent: 300.0 μm
# Dendrite diameter: 2.5 μm
# Neurotransmitters: ['AMPA', 'NMDA']
# PSP amplitudes: {'AMPA': 0.8, 'NMDA': 0.4}
# Rise times: {'AMPA': 2.0, 'NMDA': 15.0}
# Firing rates - Resting: [2.0, 8.0] Hz
# Firing rates - Active: [15.0, 40.0] Hz
# Firing rates - Maximum: [60.0, 120.0] Hz

# === NEST MODEL CREATION ===
nest.CopyModel("iaf_psc_alpha", "iaf_psc_alpha_PyL23_custom")
nest.SetDefaults("iaf_psc_alpha_PyL23_custom", {
                        "V_th": -50.0,
                        "C_m": 200.0,
                        "tau_m": 15.0,
                        "V_reset": -70.0,
                        "t_ref": 2.0,
                        "I_e": 200.0
                    })
pyl23 = nest.Create("iaf_psc_alpha_PyL23_custom", 1)

print(f"Created neuron: {pyl23}")
print(f"Model template: iaf_psc_alpha_PyL23_custom")

# === cortical_population (population_builder) ===
# Execution order: 3
# Population: Layer 2/3 Pyramidal Neurons (L23Pyr)
# Generated by NeuroWorkflow PopulationBuilderNode
# Brain Region: Primary Visual Cortex
# Population Size: 800 neurons (single hemisphere)
# Model Type: point_process
# Spatial: 3D


# === POPULATION BIOLOGICAL CONTEXT ===
# Density: 25000 neurons/mm³
# Tissue volume: 0.2 mm³
# Reference: Schüz & Palm (1989)
# Species: human
# Estimation method: stereological counting
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# === SPATIAL POSITIONS ===
# 3D positions for 800 neurons
# Spatial bounds: {'x': (0.0, 2.0), 'y': (0.0, 2.0), 'z': (0.0, 1.0)}

# Generate spatial positions
positions = np.zeros((800, 3))
positions[:, 0] = np.random.uniform(0.0, 2.0, 800)  # x coordinates
positions[:, 1] = np.random.uniform(0.0, 2.0, 800)  # y coordinates
positions[:, 2] = np.random.uniform(0.0, 1.0, 800)  # z coordinates

# === POPULATION CREATION ===
# Using neuron model from SingleNeuronBuilderNode: iaf_psc_alpha_PyL23_custom
# Create population with 3D spatial positions
nest_positions = nest.spatial.free(positions.tolist())
l23pyr = nest.Create("iaf_psc_alpha_PyL23_custom", 800, positions=nest_positions)

# Print status of one neuron from the population
neuron_status = nest.GetStatus(l23pyr[0])
print(f"Status of first neuron: {neuron_status}")

# === POPULATION SUMMARY ===
print(f"Created population: {len(l23pyr)} Layer 2/3 Pyramidal Neurons")
print(f"Population IDs: {l23pyr}")
print(f"Model: iaf_psc_alpha_PyL23_custom")
print(f"Spatial organization: 3D positions")

# === spike detector for some neurons at Inh. pop (recording_builder) ===
# Execution order: 4
# === RECORDING SETUP ===
# Generated by SNNbuilder_Recordable: spike detector for some neurons at Inh. pop
# Recording type: spike_recorder


# Spike recorder parameters
spike_params = {
    "record_to": "ascii",
    "start": 0.0,
    "stop": 1000.0
}

# Create 1 spike_recorder device(s)
recorders = nest.Create('spike_recorder', 1, params=spike_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# l23pyr = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Volume area (efficient vectorized approach - works for 2D/3D)
center_coordinates = np.array([0.0, 0.0, 0.0])
target_radius = 0.5

# Get population positions directly from NEST population
positions = nest.GetPosition(l23pyr)

# Efficient vectorized distance calculation (avoids sqrt, works for 2D/3D)
d_squared = np.sum((positions - center_coordinates)**2, axis=1)

# Create boolean mask for neurons within radius
mask = d_squared <= target_radius * target_radius

# Direct NodeCollection boolean indexing (NEST-native approach)
target_neurons = l23pyr[mask]

if len(target_neurons) == 0:
    raise ValueError(f'No neurons found within radius {target_radius} of center {center_coordinates}')

# Create connections (efficient approach)
# Recording devices: Direct connections (no synapse properties needed)
nest.Connect(target_neurons, recorders)
# Note: Recording devices receive spikes directly, no synaptic transmission

print(f'Created 1 recording devices')
print(f'Connected {len(target_neurons)} target neurons')

# === spike detector for Exc. pop (recording_builder) ===
# Execution order: 5
# === RECORDING SETUP ===
# Generated by SNNbuilder_Recordable: spike detector for Exc. pop
# Recording type: spike_recorder


# Spike recorder parameters
spike_params = {
    "record_to": "ascii",
    "start": 0.0,
    "stop": 1000.0
}

# Create 1 spike_recorder device(s)
recorders = nest.Create('spike_recorder', 1, params=spike_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# l23pyr = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Full population
target_neurons = l23pyr

# Create connections (efficient approach)
# Recording devices: Direct connections (no synapse properties needed)
nest.Connect(target_neurons, recorders)
# Note: Recording devices receive spikes directly, no synaptic transmission

print(f'Created 1 recording devices')
print(f'Connected {len(target_neurons)} target neurons')

# === direct current stimulation (stimulation_builder) ===
# Execution order: 6
# === STIMULATION SETUP ===
# Generated by SNNbuilder_Stimulation: direct current stimulation
# Stimulation type: dc_generator


# DC generator parameters
dc_params = {
    "label": "dc_stim",
    "start": 500.0,
    "stop": 700.0,
    "amplitude": 100.0
}

# Create 1 dc_generator device(s)
devices = nest.Create('dc_generator', 1, params=dc_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# l23pyr = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Volume area (efficient vectorized approach - works for 2D/3D)
center_coordinates = np.array([0.0, 0.0, 0.0])
target_radius = 0.5

# Get population positions directly from NEST population
positions = nest.GetPosition(l23pyr)

# Efficient vectorized distance calculation (avoids sqrt, works for 2D/3D)
d_squared = np.sum((positions - center_coordinates)**2, axis=1)

# Create boolean mask for neurons within radius
mask = d_squared <= target_radius * target_radius

# Direct NodeCollection boolean indexing (NEST-native approach)
target_neurons = l23pyr[mask]

if len(target_neurons) == 0:
    raise ValueError(f'No neurons found within radius {target_radius} of center {center_coordinates}')

# Create connections (efficient approach)
# DC generator: Direct current injection (no synapse properties needed)
nest.Connect(devices, target_neurons)
# Note: DC generators inject current directly, no synaptic transmission

print(f'Created 1 stimulation devices')
print(f'Connected to {{len(target_neurons)}} target neurons')

# === poisson_stimulation noise (stimulation_builder) ===
# Execution order: 7
# === STIMULATION SETUP ===
# Generated by SNNbuilder_Stimulation: poisson_stimulation noise
# Stimulation type: poisson_generator


# Poisson generator parameters
poisson_params = {
    "rate": 50.0,
    "start": 100.0,
    "stop": 900.0
}

# Synapse specification
synapse_spec = {
    "synapse_model": "static_synapse",
    "weight": 2.5,
    "delay": 1.5
}

# Create custom synapse model
custom_synapse_name = 'static_synapse_custom_poisson_stimulation_noise'
nest.CopyModel('static_synapse', custom_synapse_name)

# Create 1 poisson_generator device(s)
devices = nest.Create('poisson_generator', 1, params=poisson_params)

# Identify target neurons
# Note: Make sure you have defined your population variable:
# l23pyr = nest.Create('model_name', size, positions=nest_positions)
# Population must have spatial properties for volume area targeting

# Target: Full population
target_neurons = l23pyr

# Create connections (efficient approach)
sdict = {
    'synapse_model': custom_synapse_name,
    'weight': 2.5,
    'delay': 1.5,
    # No receptor_type needed for simple neurons
}

# Efficient connection: no need to iterate over devices
# Single Poisson device to many neurons (all-to-all)
nest.Connect(devices, target_neurons, syn_spec=sdict)

print(f'Created 1 stimulation devices')
print(f'Connected to {{len(target_neurons)}} target neurons')

# === connection from Inh to Exc Neurons (connection_builder) ===
# Execution order: 8
# Neural Connection: IE indegree
# Generated by NeuroWorkflow ConnectionBuilderNode
# Timestamp: 2026-02-02 17:10:48


# Connection: IE indegree
# Type: inhibitory
# Rule: fixed_indegree

# === SYNAPSE MODEL SETUP ===
base_synapse = 'static_synapse'
custom_synapse = 'static_synapse_custom_connection_from_Inh_to_Exc_Neurons'

# Copy base synapse model
nest.CopyModel(base_synapse, custom_synapse)

# === CONNECTION DICTIONARY ===
cdict = {'allow_autapses': False, 'rule': 'fixed_indegree', 'indegree': 1, 'allow_multapses': False, 'mask': {'spherical': {'radius': 1.0}}}

# === SYNAPSE DICTIONARY (User-defined weight) ===
# User provided weight in synapse_dict
# Target is multisynapse: False

# Simple neuron target - no receptor_type needed
sdict = {'synapse_model': 'static_synapse_custom_connection_from_Inh_to_Exc_Neurons', 'weight': -10.0, 'delay': 1.0}

# === CREATE CONNECTIONS ===
# Note: Make sure you have defined your population variables:
# pvpop = your_source_population
# l23pyr = your_target_population

# Create connections (single synapse dict - user-defined weight)
nest.Connect(pvpop, l23pyr, cdict, sdict)

# Get connection information
# connections = nest.GetConnections(pvpop, l23pyr)
# print(f'Created {{len(connections)}} connections')

# === BIOLOGICAL PROPERTIES ===
# Axon organization: focused (radius: 1.0 mm)
# Projection percentage: 100.0%
# Bouton number: 50
# Receptor location: none (None)
# Redundancy: 50.0
# Base weight: 10.0 (effective weight calculated at runtime)

# === connection from Exc. to Inh Neurons. (connection_builder) ===
# Execution order: 9
# Neural Connection: EI indegree
# Generated by NeuroWorkflow ConnectionBuilderNode
# Timestamp: 2026-02-02 17:10:48


# Connection: EI indegree
# Type: excitatory
# Rule: fixed_indegree

# === SYNAPSE MODEL SETUP ===
base_synapse = 'static_synapse'
custom_synapse = 'static_synapse_custom_connection_from_Exc._to_Inh_Neurons.'

# Copy base synapse model
nest.CopyModel(base_synapse, custom_synapse)

# === CONNECTION DICTIONARY ===
cdict = {'allow_autapses': False, 'rule': 'fixed_indegree', 'indegree': 4, 'allow_multapses': False, 'mask': {'spherical': {'radius': 0.5}}}

# === SYNAPSE DICTIONARY (User-defined weight) ===
# User provided weight in synapse_dict
# Target is multisynapse: False

# Simple neuron target - no receptor_type needed
sdict = {'synapse_model': 'static_synapse_custom_connection_from_Exc._to_Inh_Neurons.', 'weight': 4.0, 'delay': 1.0}

# === CREATE CONNECTIONS ===
# Note: Make sure you have defined your population variables:
# l23pyr = your_source_population
# pvpop = your_target_population

# Create connections (single synapse dict - user-defined weight)
nest.Connect(l23pyr, pvpop, cdict, sdict)

# Get connection information
# connections = nest.GetConnections(l23pyr, pvpop)
# print(f'Created {{len(connections)}} connections')

# === BIOLOGICAL PROPERTIES ===
# Axon organization: focused (radius: 0.5 mm)
# Projection percentage: 100.0%
# Bouton number: 50
# Receptor location: none (None)
# Redundancy: 100.0
# Base weight: 4.0 (effective weight calculated at runtime)
