# Generated by Django 5.2.13 on 2026-04-13 01:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('workflow_context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'flow_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowNode',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('position_x', models.FloatField()),
                ('position_y', models.FloatField()),
                ('node_type', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflow.flowproject')),
            ],
            options={
                'db_table': 'flow_nodes',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowEdge',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('source_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('target_handle', models.CharField(blank=True, max_length=255, null=True)),
                ('edge_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='workflow.flownode')),
                ('target_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='workflow.flownode')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflow.flowproject')),
            ],
            options={
                'db_table': 'flow_edges',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('backend', models.CharField(choices=[('local', 'Local'), ('slurm', 'Slurm'), ('jupyter', 'Jupyter')], default='jupyter', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('slurm_job_id', models.CharField(blank=True, default='', max_length=64)),
                ('exit_code', models.IntegerField(blank=True, null=True)),
                ('stdout', models.TextField(blank=True, default='')),
                ('stderr', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('resource_requests', models.JSONField(blank=True, default=dict)),
                ('remote_run_dir', models.CharField(blank=True, default='', max_length=512)),
                ('artifacts', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_runs', to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='workflow.flowproject')),
            ],
            options={
                'db_table': 'workflow_runs',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
