# Generated by Django 5.2 on 2026-01-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowproject",
            name="workflow_context",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
