# Generated by Django 5.2.13 on 2026-05-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=16),
        ),
    ]
