# Generated by Django 5.2 on 2026-04-22 23:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workflow", "0002_flowproject_workflow_context"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "backend",
                    models.CharField(
                        choices=[
                            ("local", "Local"),
                            ("slurm", "Slurm"),
                            ("jupyter", "Jupyter"),
                        ],
                        default="jupyter",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "slurm_job_id",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("exit_code", models.IntegerField(blank=True, null=True)),
                ("stdout", models.TextField(blank=True, default="")),
                ("stderr", models.TextField(blank=True, default="")),
                ("error_message", models.TextField(blank=True, default="")),
                ("resource_requests", models.JSONField(blank=True, default=dict)),
                (
                    "remote_run_dir",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("artifacts", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workflow",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="workflow.flowproject",
                    ),
                ),
            ],
            options={
                "db_table": "workflow_runs",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
