# Generated by Django 5.2.13 on 2026-05-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_workflowrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowproject',
            name='hpc_target',
            field=models.CharField(blank=True, choices=[('riken', 'Riken'), ('fugaku', 'Fugaku')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='flowproject',
            name='reference',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='flowproject',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], db_index=True, default='private', max_length=16),
        ),
    ]
