# Generated by Django 5.2.13 on 2026-05-24 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_flowproject_reference_hpc_target'),
        ('workflow', '0004_flowproject_hpc_target_flowproject_reference_and_more'),
    ]

    operations = [
    ]
