FROM python:3.11.11-slim

# jupyter
RUN pip install --no-cache-dir jupyterlab

# Set working directory
WORKDIR /app

# Copy project file
COPY . .

# Port 8888 exposed
EXPOSE 8888

# run command
CMD ["jupyter", "lab", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token='oistworkflow1234'", "--NotebookApp.password=", "--notebook-dir=/app"]
