"""
Virtual Neuromodulation (Group Surrogate model) loading nodes.

This module provides nodes for loading model data of Virtual Neuromodulation.
"""

import os
import json
import numpy as np
import h5py
import hdf5storage
import vneumodpy as vnm

from typing import Dict, Any, List, Tuple
from neuroworkflow.core.node import Node
from neuroworkflow.core.schema import NodeDefinitionSchema, PortDefinition, ParameterDefinition, MethodDefinition
from neuroworkflow.core.port import PortType


class VNMLoadGroupSurrogateModelNode(Node):
    """Virtual Neuromodulation (Group Surrogate model) Data loader node."""
    
    NODE_DEFINITION = NodeDefinitionSchema(
        type='model_loader',
        description='Loads Virtual Neuromodulation (Group Surrogate model) model data',
        parameters={
            'model_file': ParameterDefinition(
                default_value='',
                description='Group Surrogate model file (.mat file generated by MATLAB)'
            ),
            'model_path': ParameterDefinition(
                default_value='',
                description='Group Surrogate model path (files generated by vneumodpy)'
            )
        },
        outputs={
            'model': PortDefinition(
                type=PortType.OBJECT,
                description='Group Surrogate model'
            )
        },
        methods={
            'initialize_model': MethodDefinition(
                description='Initialize Group Surrogate model',
                inputs=[],
                outputs=['model']
            )
        }
    )
    
    def __init__(self, name: str):
        """Initialize Virtual Neuromodulation (Group Surrogate model).
        
        Args:
            name: Name of the node
        """
        super().__init__(name)
        self._define_process_steps()
            
        
    def _define_process_steps(self) -> None:
        """Define process steps for this node."""
        # With the new schema, we can use method_key to link directly to NODE_DEFINITION methods
        self.add_process_step(
            "initialize_model",
            self.initialize_model,
            method_key="initialize_model"
        )
        

    def initialize_model(self) -> Dict[str, Any]:
        """Loading Group Surrogate model."""
        model_file = self._parameters["model_file"]  # this is MATLAB (.mat) model file
        model_path = self._parameters["model_path"]  # this is python generated model files

        if len(model_file) > 0:
            print(f"Loading Group Surrogate model : {model_file}")
            dic = h5py.File(model_file, 'r')
            if dic.get('net') is None:
                raise FileNotFoundError(f"no group surrogate model file. please specify .mat file.: {model_file}")

            mat_net = dic['net']
            model = vnm.MultivariateVARNetwork()
            model.init_with_mat(mat_net)
            dic.close()

        elif len(model_path) > 0:
            print(f"Loading a Group Surrogate model : {model_path}")
            model = vnm.MultivariateVARNetwork()
            model.load(model_path)
        else:
            raise FileNotFoundError(f"no group surrogate model file. please specify model file.")

        return {"model": model}

