# Generated by Django 5.2.13 on 2026-04-13 01:30

import app.box.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('analysis', 'Analysis'), ('io', 'I/O'), ('optimization', 'Optimization'), ('simulation', 'Simulation'), ('network', 'Network'), ('stimulus', 'Stimulus')], default='analysis', help_text='Node category for organizing files', max_length=50)),
                ('file', models.FileField(upload_to=app.box.models.get_upload_path)),
                ('file_content', models.TextField(default='')),
                ('node_classes', models.JSONField(blank=True, default=dict)),
                ('is_analyzed', models.BooleanField(default=False)),
                ('analysis_error', models.TextField(blank=True, null=True)),
                ('file_size', models.IntegerField(default=0)),
                ('file_hash', models.CharField(default='default', max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'box_pythonfile',
                'ordering': ['-created_at'],
            },
        ),
    ]
