# Generated by Django 5.2 on 2025-11-24 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("box", "0002_alter_pythonfile_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pythonfile",
            name="category",
            field=models.CharField(
                choices=[
                    ("stimulus", "Stimulus"),
                    ("analysis", "Analysis"),
                    ("optimization", "Optimization"),
                    ("network", "Network"),
                    ("io", "I/O"),
                    ("simulation", "Simulation"),
                    ("__init__.py", "__init__.py"),
                    ("__pycache__", "__pycache__"),
                    (".ipynb_checkpoints", ".ipynb_checkpoints"),
                ],
                default="analysis",
                help_text="Node category for organizing files",
                max_length=50,
            ),
        ),
    ]
