"""
SLURM job manager implementation.
"""

import os
import subprocess
from typing import Dict, Any, Optional
from datetime import datetime

from .base import JobManager, JobStatus, JobInfo
from ...core.schema import ResourceRequirements


class SLURMJobManager(JobManager):
    """
    Job manager for SLURM (Simple Linux Utility for Resource Management).
    
    Supports common SLURM clusters and supercomputers.
    """
    
    def __init__(self, config: Optional[Dict[str, Any]] = None):
        """
        Initialize SLURM job manager.
        
        Args:
            config: Configuration dictionary with optional keys:
                - partition: SLURM partition name
                - account: Account/project name
                - time_format: Time format ('minutes', 'hours', 'days')
                - sbatch_path: Path to sbatch command (default: 'sbatch')
                - squeue_path: Path to squeue command (default: 'squeue')
        """
        super().__init__(config)
        self.partition = config.get('partition')
        self.account = config.get('account')
        self.time_format = config.get('time_format', 'hours')
        self.sbatch_path = config.get('sbatch_path', 'sbatch')
        self.squeue_path = config.get('squeue_path', 'squeue')
    
    def generate_job_script(
        self,
        python_script: str,
        resources: ResourceRequirements,
        job_name: str,
        output_dir: str = "./output",
        additional_args: Optional[Dict[str, Any]] = None
    ) -> str:
        """
        Generate SLURM job submission script.
        
        Args:
            python_script: Python script to execute
            resources: Resource requirements
            job_name: Name for the job
            output_dir: Output directory for job files
            additional_args: Additional SLURM directives
        
        Returns:
            Path to generated job script
        """
        os.makedirs(output_dir, exist_ok=True)
        script_path = os.path.join(output_dir, f"{job_name}.sh")
        
        # Convert walltime to SLURM format
        walltime_str = self._format_walltime(resources.walltime_hours)
        
        lines = [
            "#!/bin/bash",
            f"#SBATCH --job-name={job_name}",
            f"#SBATCH --output={output_dir}/{job_name}_%j.out",
            f"#SBATCH --error={output_dir}/{job_name}_%j.err",
            f"#SBATCH --ntasks={resources.tasks_per_node}",
            f"#SBATCH --cpus-per-task={resources.cpus // resources.tasks_per_node if resources.tasks_per_node > 0 else resources.cpus}",
            f"#SBATCH --mem={int(resources.memory_gb * 1024)}M",
            f"#SBATCH --time={walltime_str}",
        ]
        
        if resources.nodes > 1:
            lines.append(f"#SBATCH --nodes={resources.nodes}")
        
        if resources.gpus > 0:
            lines.append(f"#SBATCH --gres=gpu:{resources.gpus}")
        
        if self.partition:
            lines.append(f"#SBATCH --partition={self.partition}")
        elif additional_args and 'partition' in additional_args:
            lines.append(f"#SBATCH --partition={additional_args['partition']}")
        
        if self.account:
            lines.append(f"#SBATCH --account={self.account}")
        elif resources.account:
            lines.append(f"#SBATCH --account={resources.account}")
        elif additional_args and 'account' in additional_args:
            lines.append(f"#SBATCH --account={additional_args['account']}")
        
        if resources.queue:
            lines.append(f"#SBATCH --qos={resources.queue}")
        
        # Additional SLURM directives
        if additional_args:
            for key, value in additional_args.items():
                if key not in ['partition', 'account'] and not key.startswith('#'):
                    lines.append(f"#SBATCH --{key}={value}")
        
        lines.extend([
            "",
            "# Job script generated by NeuroWorkflow",
            f"# Generated: {datetime.now().isoformat()}",
            "",
            "# Load modules if needed (customize for your system)",
            "# module load python/3.9",
            "# module load nest-simulator",
            "",
            "# Run the Python script",
            f"python << 'PYTHON_SCRIPT'",
            python_script,
            "PYTHON_SCRIPT",
        ])
        
        with open(script_path, 'w') as f:
            f.write('\n'.join(lines))
        
        # Make script executable
        os.chmod(script_path, 0o755)
        
        return script_path
    
    def submit_job(self, job_script_path: str) -> str:
        """
        Submit job to SLURM using sbatch.
        
        Args:
            job_script_path: Path to job submission script
        
        Returns:
            Job ID assigned by SLURM
        """
        try:
            result = subprocess.run(
                [self.sbatch_path, job_script_path],
                capture_output=True,
                text=True,
                check=True
            )
            # Parse job ID from output (format: "Submitted batch job 12345")
            output = result.stdout.strip()
            job_id = output.split()[-1]
            return job_id
        except subprocess.CalledProcessError as e:
            raise RuntimeError(f"Failed to submit SLURM job: {e.stderr}")
        except FileNotFoundError:
            raise RuntimeError(f"SLURM command '{self.sbatch_path}' not found. Is SLURM installed?")
    
    def get_job_status(self, job_id: str) -> JobStatus:
        """
        Get current status of a SLURM job.
        
        Args:
            job_id: Job ID
        
        Returns:
            Current job status
        """
        try:
            result = subprocess.run(
                [self.squeue_path, '-j', job_id, '--format=%T', '--noheader'],
                capture_output=True,
                text=True,
                check=True
            )
            status_str = result.stdout.strip().upper()
            
            # Map SLURM status codes to JobStatus
            status_map = {
                'PENDING': JobStatus.PENDING,
                'RUNNING': JobStatus.RUNNING,
                'COMPLETED': JobStatus.COMPLETED,
                'FAILED': JobStatus.FAILED,
                'CANCELLED': JobStatus.CANCELLED,
                'TIMEOUT': JobStatus.FAILED,
            }
            
            return status_map.get(status_str, JobStatus.UNKNOWN)
        except subprocess.CalledProcessError:
            # Job not found - might be completed or never existed
            return JobStatus.UNKNOWN
        except FileNotFoundError:
            raise RuntimeError(f"SLURM command '{self.squeue_path}' not found. Is SLURM installed?")
    
    def get_job_info(self, job_id: str) -> JobInfo:
        """
        Get detailed information about a SLURM job.
        
        Args:
            job_id: Job ID
        
        Returns:
            Job information
        """
        status = self.get_job_status(job_id)
        
        # Try to get additional info from sacct (if available)
        output_path = None
        log_path = None
        
        try:
            result = subprocess.run(
                ['sacct', '-j', job_id, '--format=JobID,State,Start,End,ExitCode', '--noheader', '--parsable2'],
                capture_output=True,
                text=True,
                check=True
            )
            # Parse sacct output if available
            # Format: JobID|State|Start|End|ExitCode
            lines = result.stdout.strip().split('\n')
            if lines:
                parts = lines[0].split('|')
                if len(parts) >= 4:
                    started_at = self._parse_datetime(parts[2]) if parts[2] else None
                    completed_at = self._parse_datetime(parts[3]) if parts[3] else None
                else:
                    started_at = None
                    completed_at = None
            else:
                started_at = None
                completed_at = None
        except (subprocess.CalledProcessError, FileNotFoundError):
            started_at = None
            completed_at = None
        
        # Try to find output files
        # SLURM typically creates files like jobname_12345.out and jobname_12345.err
        # We'd need to know the job name to find these, so we'll return None for now
        
        return JobInfo(
            job_id=job_id,
            status=status,
            submitted_at=datetime.now(),  # Would need to query for actual submission time
            started_at=started_at,
            completed_at=completed_at,
            output_path=output_path,
            log_path=log_path
        )
    
    def cancel_job(self, job_id: str) -> bool:
        """
        Cancel a SLURM job using scancel.
        
        Args:
            job_id: Job ID to cancel
        
        Returns:
            True if cancellation was successful
        """
        try:
            subprocess.run(
                ['scancel', job_id],
                capture_output=True,
                check=True
            )
            return True
        except (subprocess.CalledProcessError, FileNotFoundError):
            return False
    
    def _format_walltime(self, hours: float) -> str:
        """Convert hours to SLURM time format (HH:MM:SS or D-HH:MM:SS)."""
        if self.time_format == 'minutes':
            total_minutes = int(hours * 60)
            h = total_minutes // 60
            m = total_minutes % 60
            return f"{h:02d}:{m:02d}:00"
        elif self.time_format == 'days':
            days = int(hours // 24)
            remaining_hours = int(hours % 24)
            minutes = int((hours % 1) * 60)
            return f"{days}-{remaining_hours:02d}:{minutes:02d}:00"
        else:  # hours (default)
            h = int(hours)
            m = int((hours % 1) * 60)
            return f"{h:02d}:{m:02d}:00"
    
    def _parse_datetime(self, date_str: str) -> Optional[datetime]:
        """Parse SLURM datetime string."""
        try:
            # SLURM typically uses format: YYYY-MM-DDTHH:MM:SS
            return datetime.fromisoformat(date_str.replace('T', ' '))
        except (ValueError, AttributeError):
            return None

